[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/usr/local/bin/railway-homeassistant-entrypoint"
healthcheckPath = "/manifest.json"
healthcheckTimeout = 1800
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
